import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import GradualBlur from "@/components/GradualBlur";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle";
import { ProgressBar } from "@/components/progress-bar";
import { NavigationMenuDemo } from "@/components/navigation-menu-demo";

const geistSans = Geist({
variable: "--font-geist-sans",
subsets: ["latin"],
});

const geistMono = Geist_Mono({
variable: "--font-geist-mono",
subsets: ["latin"],
});

export const metadata: Metadata = {
title: {
    default: "Neo-Classical Literature",
    template: "%s | Neo-Classical Literature",
},
description: "Generated by Neo-Classical Literature",
};

export default function RootLayout({
children,
}: Readonly<{ children: React.ReactNode; }>) {
    return (
    <html lang="en" className="dark" suppressHydrationWarning>

    <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
            <ProgressBar />
            {/* Navbar */}
            <nav
                className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                <div className="container mx-auto px-4">
                    <div className="flex h-16 items-center justify-between">
                        <div className="flex items-center gap-2">
                            <Link href="/" className="text-xl font-bold hover:underline">
                                Great Books
                            </Link>
                        </div>

                        <div className="hidden md:flex flex-1 justify-center">
                            <NavigationMenuDemo />
                        </div>

                        <div className="flex items-center gap-4">
                            <ModeToggle />
                        </div>
                    </div>
                </div>
            </nav>

            {children}
        </ThemeProvider>
        <GradualBlur target="page" position="bottom" height="4rem" strength={1} divCount={5} curve="bezier"
            exponential={true} opacity={1} />
    </body>

    </html>
    );
    }
